### PR TITLE
Fix: Set `read_options` to nil to ensure the correct function signature and prevent runtime errors.

### PR DESCRIPTION
**Pull request by GarupanOjisan**
When running the spanner-change-streams-tail command, the following error would occur:

```
$ spanner-change-streams-tail --project=my-project --instance=my-instance --database=my-db --stream=streams
Reading the stream...
failed to read stream: spanner: code = "InvalidArgument", desc = "No matching signature for READ_streams\\n  Argument types: TIMESTAMP, INT64, STRING, INT64\\n  Signature: READ_ESSYNCSTREAMS(start_timestamp => TIMESTAMP, end_timestamp => TIMESTAMP, partition_token => STRING, heartbeat_milliseconds => INT64, read_options => ARRAY<STRING>)\\n    Signature requires at least 5 arguments, found 4 arguments [at 1:26]\\nSELECT ChangeRecord FROM READ_streams(@start_timestamp, @end_timestamp,...\\n                         ^"
```

The `READ_*` function requires a `read_options` parameter to match the expected function signature. Without it, the query execution fails. To resolve this issue, this PR explicitly sets `read_options` to nil to ensure the query has the correct number of parameters and avoids the runtime error.

### CODE REVIEW

**Comment by yfuruyama** [comment]
@GarupanOjisan Thank you for filing this fix.

I was trying to reproduce, but I couldn't make it. Does the error happen in every database/stream?

**Comment by yfuruyama** [comment]
This was the temporal issue in Spanner side where the `read_options` parameter was regarded as required parameter although it's actually an optional parameter. Now it has been mitigated, so we can close this PR. Sorry for the confusion.

**Comment by yfuruyama** [comment]
This was the temporal issue in Spanner side where the `read_options` parameter is regarded as required parameter although it's actually an optional parameter. Now it has been mitigated, so we can close this PR. Sorry for the confusion.

**Comment by GarupanOjisan** [comment]
@yfuruyama 
Thank you for answering. 
We received a similar notice from our Google contact as well. I’ll  close this PR.

**Pull request closed without merging**
